#!/usr/bin/env bash
echo "Building BitPay Plugin Directory..."
rm -rf wpsc-merchants
mkdir wpsc-merchants
mkdir wpsc-merchants/bitpay
mkdir wpsc-merchants/bitpay/lib
cp -avr src/assets wpsc-merchants/bitpay > /dev/null
cp -avr src/templates wpsc-merchants/bitpay > /dev/null
cp src/bitpay.merchant.php wpsc-merchants/ > /dev/null
cp LICENSE wpsc-merchants/ > /dev/null
cp README.md wpsc-merchants/ > /dev/null
cp CHANGELOG wpsc-merchants/ > /dev/null
cp -avr vendor/bitpay/php-client/src/* wpsc-merchants/bitpay/lib > /dev/null
echo "Setup finished"